// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFZfVWulELRGOz0ylAeoV9ui9NRqu9p9E',
    appId: '1:895032135228:web:87cd58e34f24f936f17d39',
    messagingSenderId: '895032135228',
    projectId: 'techsolutions-app',
    authDomain: 'techsolutions-app.firebaseapp.com',
    storageBucket: 'techsolutions-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrdvYCUNbDbAGXuLQ9SZkS7HgrqTBlHd8',
    appId: '1:895032135228:android:f1e08c5d49753028f17d39',
    messagingSenderId: '895032135228',
    projectId: 'techsolutions-app',
    storageBucket: 'techsolutions-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwsPFZnRPqWAvSLHR7iJ3XQqq9tLH4-DE',
    appId: '1:895032135228:ios:ae6d1acf291be4f5f17d39',
    messagingSenderId: '895032135228',
    projectId: 'techsolutions-app',
    storageBucket: 'techsolutions-app.firebasestorage.app',
    iosBundleId: 'com.example.techsolutionsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwsPFZnRPqWAvSLHR7iJ3XQqq9tLH4-DE',
    appId: '1:895032135228:ios:ae6d1acf291be4f5f17d39',
    messagingSenderId: '895032135228',
    projectId: 'techsolutions-app',
    storageBucket: 'techsolutions-app.firebasestorage.app',
    iosBundleId: 'com.example.techsolutionsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFZfVWulELRGOz0ylAeoV9ui9NRqu9p9E',
    appId: '1:895032135228:web:8ff7bc364d96bbb7f17d39',
    messagingSenderId: '895032135228',
    projectId: 'techsolutions-app',
    authDomain: 'techsolutions-app.firebaseapp.com',
    storageBucket: 'techsolutions-app.firebasestorage.app',
  );
}
